name: GitHub Classroom Workflow

on:
  push: 
    branches: 
      - '**/issue**'

permissions:
  checks: write
  actions: read
  contents: read



jobs:
  mainline:
    name: 'mainline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The key is" \\${{ github.sha }} 

  verify_issue:
    runs-on: ubuntu-latest
    name: 'Verify issue'
    steps:
      - uses: actions/checkout@v2
      - run: echo $ISSUE 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue }}

  if_merged:
    if: github.event.pull_request.merged == true
      name: 'Check if merge is possible'
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo The PR was merged
        
       
    
    

  
