name: GitHub Classroom Workflow

on:
  push: 
    branches: 
      - '**/issue**'

permissions:
  checks: write
  actions: read
  contents: read



jobs:
  mainline:
    name: 'mainline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The key is" \\${{ github.sha }} 

  verify_issue:
    runs-on: ubuntu-latest
    name: 'Verify issue'
    steps:
      - uses: actions/checkout@v2
      - run: echo "URL:" \\${{ github.event.issue.html_url }}
        
       
    
    

  
