name: GitHub Classroom Workflow

on:
  push: 
    branches: 
      - '**/issue**'

permissions:
  checks: write
  actions: read
  contents: read



jobs:
  mainline:
    name: 'mainline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The key is" \\${{ github.sha }} 

  verify_issue:
    runs-on: ubuntu-latest
    name: 'Verify issue'
    steps:
      - uses: actions/checkout@v2
      - run: echo $ISSUE 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue }}

  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Issue Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check for merge conflicts
        run: |
          git fetch origin master
          git merge-base --is-ancestor HEAD origin/master
          if [ $? -eq 0 ]; then
            echo "No merge conflicts found"
          else
            echo "There are merge conflicts, please resolve them"
            exit 1
          fi
        
       
    
    

  
