name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  mainline:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The key is" \\${{ github.sha }} 

  verify_issue:
    runs-on: ubuntu-latest
    
    if: startsWith(github.ref, 'refs/heads/issue/') # Only run for issue branches
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
      env:
        ISSUE: ${{ github.event.issue.html_url }}
    - name: Check merge conflicts
      run: git merge --no-commit --no-ff master

  
